#
# Default servers
#
comas.1=comas.cogerent.com
comas.2=comas-master.cogerent.com
comas.3=comas-its.cogerent.com
comas.4=comas-its2.cogerent.com
comas.5=comas-its3.cogerent.com
comas.6=comas-its4.cogerent.com