package edu.carleton.cas.jetty.embedded;

import com.cogerent.utility.PropertyValue;
import edu.carleton.cas.constants.ClientShared;
import edu.carleton.cas.exam.Invigilator;
import edu.carleton.cas.exam.InvigilatorState;
import edu.carleton.cas.file.Utils;
import edu.carleton.cas.reporting.ReportManager;
import edu.carleton.cas.ui.DisappearingAlert;
import edu.carleton.cas.ui.WebAlert;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.TimerTask;

public class ClosedBrowserScenarioTimerTask extends TimerTask {
   private static final String DEFAULT_MESSAGE = "You may have closed the browser instead of quitting.\nBrowser will open with last session context.\n\nPlease quit by pressing the Quit button";
   private static final String DEFAULT_MESSAGE_WITH_AUTOQUIT = "You may have closed the browser instead of quitting.\n\nYour session will now end";
   private final Invigilator invigilator;

   public ClosedBrowserScenarioTimerTask(Invigilator invigilator) {
      this.invigilator = invigilator;
   }

   public void run() {
      final ServletProcessor sp = this.invigilator.getServletProcessor();
      long timeout = (long)(Utils.getIntegerOrDefaultInRange(this.invigilator.getProperties(), "session.browser_inactivity", 120, 0, 300) * 1000);
      if (timeout != 0L) {
         if (sp.getTimeSinceLastAccessInMillis() > timeout) {
            if (this.invigilator.isInInvigilatorState(InvigilatorState.loggingIn)) {
               this.invigilator.setInvigilatorState(InvigilatorState.ending);
               Thread t = new Thread(new SessionEndTask(this.invigilator, ProgressServlet.getSingleton()));
               t.start();
            } else if (this.invigilator.isInInvigilatorState(InvigilatorState.choosing)) {
               this.invigilator.setInvigilatorState(InvigilatorState.ending);
               Thread t = new Thread(new SessionEndTask(this.invigilator, ProgressServlet.getSingleton(), String.format("Session ended because %s was inactive for %.03f seconds while choosing activity", this.invigilator.getNameAndID(), (double)sp.getTimeSinceLastAccessInMillis() / (double)1000.0F)));
               t.start();
            } else {
               DisappearingAlert da = new DisappearingAlert((long)ClientShared.DISAPPEARING_ALERT_TIMEOUT, 1);
               Runnable action = new Runnable() {
                  public void run() {
                     if (ClosedBrowserScenarioTimerTask.this.invigilator.isInInvigilatorState(InvigilatorState.running) && Utils.getBooleanOrDefault(ClosedBrowserScenarioTimerTask.this.invigilator.getProperties(), "session.browser_inactivity.action", true)) {
                        ReportManager reportManager = ClosedBrowserScenarioTimerTask.this.invigilator.getReportManager();
                        if (reportManager != null) {
                           String report = PropertyValue.getValue(ClosedBrowserScenarioTimerTask.this.invigilator, "session", "browser_inactivity.report", "activity");
                           reportManager.generateReport(report, ClosedBrowserScenarioTimerTask.this.invigilator.highPriorityLogArchiver, "Generated by lack of activity by " + ClosedBrowserScenarioTimerTask.this.invigilator.getNameAndID());
                        }
                     }

                     if (Utils.getBooleanOrDefault(ClosedBrowserScenarioTimerTask.this.invigilator.getProperties(), "session.browser_inactivity.quit", false)) {
                        Thread t = new Thread(new SessionEndTask(ClosedBrowserScenarioTimerTask.this.invigilator, ProgressServlet.getSingleton(), "Session ended because " + ClosedBrowserScenarioTimerTask.this.invigilator.getNameAndID() + " closed browser and auto-quit was enabled"));
                        t.start();
                     } else {
                        String path = ClosedBrowserScenarioTimerTask.this.invigilator.getServletProcessor().getRouter().getRedirect();
                        String location;
                        if (path != null && !ClosedBrowserScenarioTimerTask.this.invigilator.isInInvigilatorState(InvigilatorState.running)) {
                           String var9 = sp.getService();
                           location = var9 + path.substring(1);
                        } else {
                           location = PropertyValue.getValue(ClosedBrowserScenarioTimerTask.this.invigilator, "session", "browser_inactivity.url", (String)null);
                           if (location == null) {
                              location = Utils.getStringOrDefault(ClosedBrowserScenarioTimerTask.this.invigilator.getProperties(), "session." + String.valueOf(ClientShared.getOS()) + ".browser_inactivity.url", sp.getService());
                           }

                           location = ClosedBrowserScenarioTimerTask.this.invigilator.resolveVariablesInMessage(location);
                           if (location.startsWith("/")) {
                              String var10000 = sp.getHost();
                              location = var10000 + ":" + sp.getPort() + location;
                           }
                        }

                        try {
                           Desktop.getDesktop().browse(new URI(location));
                        } catch (URISyntaxException | UnsupportedOperationException | IOException var4) {
                           WebAlert.warning("Could not create session browser pages");
                        }
                     }

                  }
               };
               da.setRunOnCloseRegardless(action);
               String msg;
               if (Utils.getBooleanOrDefault(this.invigilator.getProperties(), "session.browser_inactivity.quit", false)) {
                  msg = "You may have closed the browser instead of quitting.\n\nYour session will now end";
               } else {
                  msg = this.invigilator.getPropertyWithVariables("session.browser_inactivity.message", "You may have closed the browser instead of quitting.\nBrowser will open with last session context.\n\nPlease quit by pressing the Quit button");
               }

               da.show(msg);
            }
         }

      }
   }
}
