package edu.carleton.cas.jetty.embedded.processors;

import edu.carleton.cas.constants.ClientShared;
import edu.carleton.cas.jetty.embedded.ServletProcessor;
import edu.carleton.cas.logging.Logger;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class MultipleChoiceQuestionProcessor implements ProcessorInterface {
   ServletProcessor servletProcessor;
   String fileName;

   public MultipleChoiceQuestionProcessor(ServletProcessor servletProcessor, String fileName) {
      this.servletProcessor = servletProcessor;
      this.fileName = fileName;
   }

   public void process(HttpServletRequest request, HttpServletResponse response) throws IOException {
      Enumeration<String> mapn = request.getParameterNames();
      String[] questionFileName = request.getParameterValues("QUESTION");
      if (questionFileName != null && questionFileName.length != 0) {
         PrintWriter answerFile = null;
         boolean var10 = false;

         try {
            var10 = true;
            String var10002 = ClientShared.getExamDirectory(this.servletProcessor.getInvigilator().getCourse(), this.servletProcessor.getInvigilator().getActivity());
            answerFile = new PrintWriter(var10002 + File.separator + this.fileName + ".txt");
            answerFile.append("# Generated by CoMaS on ");
            answerFile.append((new Date()).toString());
            answerFile.append(". DO NOT EDIT\n");

            while(mapn.hasMoreElements()) {
               String name = (String)mapn.nextElement();
               String value = request.getParameterValues(name)[0];
               if (!name.equalsIgnoreCase("QUESTION") && !name.equalsIgnoreCase("QUESTION_FILE")) {
                  answerFile.append(name);
                  answerFile.append("=");
                  answerFile.append(value);
                  answerFile.append("\n");
               }
            }

            var10 = false;
         } finally {
            if (var10) {
               response.setContentType("text/plain");
               response.addHeader("Access-Control-Allow-Origin", "*");
               response.setStatus(200);
               if (answerFile != null) {
                  if (answerFile.checkError()) {
                     response.getWriter().println("Answers not saved for " + questionFileName[0]);
                  } else {
                     response.getWriter().println("Saved answers for " + questionFileName[0]);
                  }

                  answerFile.close();
               } else {
                  response.getWriter().println("An answer file could not be created for " + questionFileName[0]);
               }

            }
         }

         response.setContentType("text/plain");
         response.addHeader("Access-Control-Allow-Origin", "*");
         response.setStatus(200);
         if (answerFile != null) {
            if (answerFile.checkError()) {
               response.getWriter().println("Answers not saved for " + questionFileName[0]);
            } else {
               response.getWriter().println("Saved answers for " + questionFileName[0]);
            }

            answerFile.close();
         } else {
            response.getWriter().println("An answer file could not be created for " + questionFileName[0]);
         }
      } else {
         String name;
         for(name = ""; mapn.hasMoreElements(); name = name + " " + (String)mapn.nextElement()) {
         }

         Logger.log(Level.SEVERE, "Unknown question processed: ", name);
         response.setContentType("text/html");
         response.addHeader("Access-Control-Allow-Origin", "*");
         response.setStatus(200);
         response.getWriter().println("<h1>No question name found</h1>");
      }

   }
}
